server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: artist-service
          uri: http://localhost:8083
          predicates:
            - Path=/artists/**
        - id: media-service
          uri: http://localhost:8082
          predicates:
            - Path=/media/**
        - id: actions-service
          uri: http://localhost:8084
          predicates:
            - Path=/actions/**
        - id: recommendation-service
          uri: http://localhost:8085
          predicates:
            - Path=/recommendations/**