server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8001
          predicates:
            - Path=/auth/**
        - id: artist-service
          uri: http://localhost:8002
          predicates:
            - Path=/artists/**
        - id: media-service
          uri: http://localhost:8003
          predicates:
            - Path=/media/**
        - id: actions-service
          uri: http://localhost:8004
          predicates:
            - Path=/actions/**