server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: artist-service
          uri: http://localhost:8082
          predicates:
            - Path=/artists/**
        - id: media-service
          uri: http://localhost:8083
          predicates:
            - Path=/media/**
        - id: actions-service
          uri: http://localhost:8084
          predicates:
            - Path=/actions/**