server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: users-service
          uri: ${USERS_SERVICE_URL}
          predicates:
            - Path=/auth/**
        - id: media-service
          uri: ${MEDIA_SERVICE_URL}
          predicates:
            - Path=/media/**
        - id: artist-service
          uri: ${ARTIST_SERVICE_URL}
          predicates:
            - Path=/artists/**
        - id: actions-service
          uri: ${ACTIONS_SERVICE_URL}
          predicates:
            - Path=/actions/**
        - id: recommendation-service
          uri: ${RECOMMENDATIONS_SERVICE_URL}
          predicates:
            - Path=/recommendations/**

jwt:
  secret:
    ${JWT_SECRET}