server:
  port: ${HTTPS_SERVER_PORT}
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: ${KEY_STORE_TYPE}
    key-alias: ${KEY_ALIAS}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${HTTP_CLIENT_URL}
              - ${HTTPS_CLIENT_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: users-service
          uri: ${USERS_SERVICE_URL}
          predicates:
            - Path=/auth/**
        - id: media-service
          uri: ${MEDIA_SERVICE_URL}
          predicates:
            - Path=/media/**
        - id: artist-service
          uri: ${ARTIST_SERVICE_URL}
          predicates:
            - Path=/artists/**
        - id: actions-service
          uri: ${ACTIONS_SERVICE_URL}
          predicates:
            - Path=/likes/**, /follows/**
        - id: recommendation-service
          uri: ${RECOMMENDATIONS_SERVICE_URL}
          predicates:
            - Path=/recommendations/**

jwt:
  secret:
    ${JWT_SECRET}